#!/usr/bin/env bash
export PANCAKE_OPTS="--citeproc --pdf-engine xelatex --template uni.latex"
export PANCAKE_HEADERS="---
header-includes: |
  \usepackage{hyperref}
  \usepackage{xepersian}
  \settextfont{Bidad}
  \setlatintextfont{Bidad}
title:
mainauthor:
author: $PANCAKE_AUTHOR
prof:
logo: $HOME/Pictures/unilogo.png
institute: $PANCAKE_INSTITUTE
---
"
. "$(dirname "$0")/pancake-init"
