#!/usr/bin/env bash
[ $# -lt 1 ]  && {
  >&2 echo "Usage: pancake init INITDIR"
  exit 1
}

DIR=$1
PANCAKE_NAME=${2:-$PANCAKE_NAME}
[ -d "$DIR" ] || mkdir -p "$DIR"
OPTS_FILE=$DIR/${PANCAKE_OPTS_FILE:-pandoc-opts}
OPTS=${PANCAKE_OPTS:---citeproc}
MD_FILE=$DIR/${PANCAKE_NAME:-main}.md
HEADERS=${PANCAKE_HEADERS:-"---\ntitle:\nauthor: $PANCAKE_AUTHOR\n---\n"}

if [ -f "$OPTS_FILE" ]; then
  >&2 echo \"$OPTS_FILE\" exists
  exit 1
fi

if [ -f "$MD_FILE" ]; then
  >&2 echo \"$MD_FILE\" exists
  exit 1
fi

echo "$OPTS" > "$OPTS_FILE"
echo -e "$HEADERS" > "$MD_FILE"
